config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#index"

  resources :groupinterests
  resources :userevents
  resources :userinterests
  resources :usergroups
  resources :interests
  resources :comments
  resources :events
  resources :groups
  resources :users
  resources :sessions

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :usergroup
  has_many :interests, through: :groupinterest
  has_many :events
  

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

#ForDrop Down Menu in Citys
CITYS = ["Alex", "Cairo", "SharmElsheik", "Menofia"]

#FOR search by citys
def self.search(search)
  where("city LIKE ?", "%#{search}%")
  # where("content LIKE ?", "%#{search}%")
end

#TO search by distance
geocoded_by :name, :latitude => :lat, :longitude => :lng
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    if params[:search]
    @groups = Group.search(params[:search]).order("created_at DESC")
  else
    @groups = Group.all.order('created_at DESC')
  end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
     @usergroup = Usergroup.new
    @allgroupusers = Usergroup.where("group_id = ?", @group.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id, :desc, :memberName, :city, :lng, :lat, :avatar)
    end


     # @locations = Location.near([30.192253100000002, 29.905788599999998], 100)
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<!DOCTYPE html>
<html>
<body>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">

 <%= f.hidden_field :user_id ,value:current_user.id  %> 
    
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :MemberName %><br>
    <%= f.text_area :memberName %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.select :city, Group::CITYS.map { |s| [("#{s}"), s] } %>
  </div>
  <div class="field">  
  <%= f.hidden_field :lng , id:"lng" %>
  </div>

  <div class="field">
  <%= f.hidden_field :lat  , id:"lat" %> 
  </div>

  <!-- photo -->
    <div class="field">
  <%= f.label :uploadPhoto %><br />
   <%= f.file_field :avatar %>
    </div>


    <!--  ALL interested will be here -->

    <div class="actions">
    <%= f.label :Interestes%><br>
<%= select_tag "interests[]", options_from_collection_for_select(Interest.all, "id", "name"), :multiple => true, :id => "vacancy_ids", :class => "form-control" %>
</div>

   
<div class="actions">
    <%= f.submit %>
  </div>


<p id="demo"></p>


<script>
// window.onload = function(){getLocation();};
var x = document.getElementById("demo");
var latt = document.getElementById("lat");
var lngt = document.getElementById("lng");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }

}

function showPosition(position) {
    x.innerHTML = "Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude; 

     
    latt.value= position.coords.latitude ;
    lngt.value= position.coords.longitude;

}
     window.onload = getLocation;
</script>



<!-- .. -->
  
<% end %>
</body>
</html>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th>Desc</th>
      <th>MemberName</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </th.ead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td> <%= group.user.username %></td>
        <td><%= group.desc %></td>
        <td><%= group.memberName %></td>
        <td><%= group.city %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } if admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Event', new_event_path %>

<%= form_for(@usergroup) do |f| %>
  

  <div class="field">
  
    <%= f.hidden_field :user_id ,value: current_user.id %>
  </div>

    <%= f.hidden_field :group_id ,value: @group.id %>

  <div class="actions">
    <%= f.submit value: "Join Event" %>
  </div>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= link_to @group.user.username, @group.user %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @group.desc %>
</p>

<p>
  <strong>MemberName:</strong>
  <%= @group.memberName %>
</p>
<p>
  <strong>City:</strong>
  <%= @group.city %>
</p>


<p>
<%= image_tag @group.avatar.url %>


</p>
  
 

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

<br/>


<br>
  <strong>Groups Events:</strong>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Describtion</th>
      <th>Image</th>
      <th>Meet Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>




<tbody>
    <% @group.events.each do |event| %>
      <tr>
        <td><%= link_to event.name ,event %></td>
        <td><%= event.desc %></td>
        <%= image_tag event.avatar.url %>
        <td><%= event.meetDate %></td>
        

      </tr>
    <% end %>
  </tbody>
</table>



<br><br></br>
<p>
<strong>Group Users:</strong>
</p>

<% @allgroupusers.each do |usr| %>
    <%= link_to usr.user.username, usr.user %>


<% end %>