config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#index"

  resources :groupinterests
  resources :userevents
  resources :userinterests
  resources :usergroups
  resources :interests
  resources :comments
  resources :events
  resources :groups
  resources :users
  resources :sessions

end

app/models/userevent.rb
class Userevent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/userevents_controller.rb
class UsereventsController < ApplicationController
  before_action :set_userevent, only: [:show, :edit, :update, :destroy]

  # GET /userevents
  # GET /userevents.json
  def index
    @userevent = Userevent.all
  end

  # GET /userevents/1
  # GET /userevents/1.json
  def show
  end

  # GET /userevents/new
  def new
    @userevent = Userevent.new
  end

  # GET /userevents/1/edit
  def edit
  end

  # POST /userevents
  # POST /userevents.json
  def create
    @userevent = Userevent.new(userevent_params)

    respond_to do |format|
      if @userevent.save
        format.html { redirect_to @userevent, notice: 'Userevent was successfully created.' }
        format.json { render :show, status: :created, location: @userevent }
      else
        format.html { render :new }
        format.json { render json: @userevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userevents/1
  # PATCH/PUT /userevents/1.json
  def update
    respond_to do |format|
      if @userevent.update(userevent_params)
        format.html { redirect_to @userevent, notice: 'Userevent was successfully updated.' }
        format.json { render :show, status: :ok, location: @userevent }
      else
        format.html { render :edit }
        format.json { render json: @userevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userevents/1
  # DELETE /userevents/1.json
  def destroy
    @userevent.destroy
    respond_to do |format|
      format.html { redirect_to userevents_url, notice: 'Userevent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userevent
      @userevent = Userevent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userevent_params
      params.require(:userevent).permit(:user_id, :event_id)
    end
end

app/helpers/userevents_helper.rb
module UsereventsHelper
end

app/views/userevents/_form.html.erb
<%= form_for(@userevent) do |f| %>
  <% if @userevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userevent.errors.count, "error") %> prohibited this userevent from being saved:</h2>

      <ul>
      <% @userevent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userevents/edit.html.erb
<h1>Editing Userevent</h1>

<%= render 'form' %>

<%= link_to 'Show', @userevent %> |
<%= link_to 'Back', userevents_path %>

app/views/userevents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Userevents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userevents.each do |userevent| %>
      <tr>
        <td><%= userevent.user %></td>
        <td><%= userevent.event %></td>
        <td><%= link_to 'Show', userevent %></td>
        <td><%= link_to 'Edit', edit_userevent_path(userevent) %></td>
        <td><%= link_to 'Destroy', userevent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userevent', new_userevent_path %>

app/views/userevents/new.html.erb
<h1>New Userevent</h1>

<%= render 'form' %>

<%= link_to 'Back', userevents_path %>

app/views/userevents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @userevent.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @userevent.event %>
</p>

<%= link_to 'Edit', edit_userevent_path(@userevent) %> |
<%= link_to 'Back', userevents_path %>