config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#index"

  resources :groupinterests
  resources :userevents
  resources :userinterests
  resources :usergroups
  resources :interests
  resources :comments
  resources :events
  resources :groups
  resources :users
  resources :sessions

end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :users, through: :userinterest
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :desc)
    end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.name %></td>
        <td><%= interest.desc %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @interest.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @interest.desc %>
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>